 =========================================================================
 i T O U G H 2 _ 17  R U N  date: Mon Feb 25 17:57:21 WST 2013
 =========================================================================

Command submitted: /home/flo/bin/itough2 -tough2 -no_delete -m MESH CO2_fwd.dat 17

STOP iTOUGH2 stopped in iTOUGH2Wrapper

 ---     0 error(s) and  0 warning(s) detected

 Machine dependent real constants used in iTOUGH2
 ------------------------------------------------

 XZERO                      :         0.1000000000E-49
 EPS                        :         0.1000000000E-09
 XINF                       :         0.1000000000E+51

 HAVE READ UNKNOWN BLOCK LABEL "----*" --- IGNORE THIS, AND CONTINUE READING INPUT DATA
 HAVE READ UNKNOWN BLOCK LABEL "     " --- IGNORE THIS, AND CONTINUE READING INPUT DATA
 HAVE READ UNKNOWN BLOCK LABEL "     " --- IGNORE THIS, AND CONTINUE READING INPUT DATA

 PRIMARY VARIABLE NO. 2 HOLDS SATURATION (RIGHT?)
 FLOPP:   1   0.9949874371066200E+00   0.4974937185533100E+00   0.1492481155659930E+01   0.4974937185533100E+00
 FLOPP:   2   0.9949874371066200E+00   0.2487468592766550E+00   0.1243734296383275E+01   0.2487468592766550E+00
 FLOPP:   3   0.9949874371066200E+00   0.1243734296383275E+00   0.1119360866744948E+01   0.1243734296383275E+00
 FLOPP:   4   0.9949874371066200E+00   0.6218671481916375E-01   0.1057174151925784E+01   0.6218671481916382E-01
 FLOPP:   5   0.9949874371066200E+00   0.3109335740958187E-01   0.1026080794516202E+01   0.3109335740958186E-01
 FLOPP:   6   0.9949874371066200E+00   0.1554667870479094E-01   0.1010534115811411E+01   0.1554667870479098E-01
 FLOPP:   7   0.9949874371066200E+00   0.7773339352395468E-02   0.1002760776459015E+01   0.7773339352395436E-02
 FLOPP:   8   0.9949874371066200E+00   0.3886669676197734E-02   0.9988741067828177E+00   0.3886669676197774E-02
 FLOPP:   9   0.9949874371066200E+00   0.1943334838098867E-02   0.9969307719447188E+00   0.1943334838098831E-02
 FLOPP:  10   0.9949874371066200E+00   0.9716674190494336E-03   0.9959591045256694E+00   0.9716674190494157E-03
 FLOPP:  11   0.9949874371066200E+00   0.4858337095247168E-03   0.9954732708161447E+00   0.4858337095247078E-03
 FLOPP:  12   0.9949874371066200E+00   0.2429168547623584E-03   0.9952303539613824E+00   0.2429168547624094E-03
 FLOPP:  13   0.9949874371066200E+00   0.1214584273811792E-03   0.9951088955340012E+00   0.1214584273812047E-03
 FLOPP:  14   0.9949874371066200E+00   0.6072921369058960E-04   0.9950481663203106E+00   0.6072921369060236E-04
 FLOPP:  15   0.9949874371066200E+00   0.3036460684529480E-04   0.9950178017134652E+00   0.3036460684524567E-04
 FLOPP:  16   0.9949874371066200E+00   0.1518230342264740E-04   0.9950026194100426E+00   0.1518230342267834E-04
 FLOPP:  17   0.9949874371066200E+00   0.7591151711323700E-05   0.9949950282583313E+00   0.7591151711339172E-05
 FLOPP:  18   0.9949874371066200E+00   0.3795575855661850E-05   0.9949912326824756E+00   0.3795575855614075E-05
 FLOPP:  19   0.9949874371066200E+00   0.1897787927830925E-05   0.9949893348945478E+00   0.1897787927807038E-05
 FLOPP:  20   0.9949874371066200E+00   0.9488939639154625E-06   0.9949883860005839E+00   0.9488939639590299E-06
 FLOPP:  21   0.9949874371066200E+00   0.4744469819577312E-06   0.9949879115536019E+00   0.4744469819240038E-06
 FLOPP:  22   0.9949874371066200E+00   0.2372234909788656E-06   0.9949876743301109E+00   0.2372234909620019E-06
 FLOPP:  23   0.9949874371066200E+00   0.1186117454894328E-06   0.9949875557183655E+00   0.1186117455365121E-06
 FLOPP:  24   0.9949874371066200E+00   0.5930587274471640E-07   0.9949874964124927E+00   0.5930587276825605E-07
 FLOPP:  25   0.9949874371066200E+00   0.2965293637235820E-07   0.9949874667595563E+00   0.2965293632861687E-07
 FLOPP:  26   0.9949874371066200E+00   0.1482646818617910E-07   0.9949874519330881E+00   0.1482646816430844E-07
 FLOPP:  27   0.9949874371066200E+00   0.7413234093089550E-08   0.9949874445198541E+00   0.7413234137665370E-08
 FLOPP:  28   0.9949874371066200E+00   0.3706617046544775E-08   0.9949874408132370E+00   0.3706617013321534E-08
 FLOPP:  29   0.9949874371066200E+00   0.1853308523272388E-08   0.9949874389599285E+00   0.1853308506660767E-08
 FLOPP:  30   0.9949874371066200E+00   0.9266542616361938E-09   0.9949874380332743E+00   0.9266543088415347E-09
 FLOPP:  31   0.9949874371066200E+00   0.4633271308180969E-09   0.9949874375699471E+00   0.4633271544207673E-09
 FLOPP:  32   0.9949874371066200E+00   0.2316635654090485E-09   0.9949874373382835E+00   0.2316635772103837E-09
 FLOPP:  33   0.9949874371066200E+00   0.1158317827045242E-09   0.9949874372224518E+00   0.1158317886051918E-09
 FLOPP:  34   0.9949874371066200E+00   0.5791589135226211E-10   0.9949874371645359E+00   0.5791589430259592E-10
 FLOPP:  35   0.9949874371066200E+00   0.2895794567613106E-10   0.9949874371355779E+00   0.2895794715129796E-10
 FLOPP:  36   0.9949874371066200E+00   0.1447897283806553E-10   0.9949874371210989E+00   0.1447897357564898E-10
 FLOPP:  37   0.9949874371066200E+00   0.7239486419032764E-11   0.9949874371138594E+00   0.7239431276673258E-11
 FLOPP:  38   0.9949874371066200E+00   0.3619743209516382E-11   0.9949874371102397E+00   0.3619771149487860E-11
 FLOPP:  39   0.9949874371066200E+00   0.1809871604758191E-11   0.9949874371084299E+00   0.1809885574743930E-11
 FLOPP:  40   0.9949874371066200E+00   0.9049358023790955E-12   0.9949874371075249E+00   0.9049427873719651E-12
 FLOPP:  41   0.9949874371066200E+00   0.4524679011895478E-12   0.9949874371070724E+00   0.4524158825347513E-12
 FLOPP:  42   0.9949874371066200E+00   0.2262339505947739E-12   0.9949874371068462E+00   0.2262634524186069E-12
 FLOPP:  43   0.9949874371066200E+00   0.1131169752973869E-12   0.9949874371067331E+00   0.1131317262093035E-12
 FLOPP:  44   0.9949874371066200E+00   0.5655848764869347E-13   0.9949874371066765E+00   0.5651035195342047E-13
 FLOPP:  45   0.9949874371066200E+00   0.2827924382434673E-13   0.9949874371066483E+00   0.2831068712794149E-13
 FLOPP:  46   0.9949874371066200E+00   0.1413962191217337E-13   0.9949874371066341E+00   0.1409983241273949E-13
 FLOPP:  47   0.9949874371066200E+00   0.7069810956086684E-14   0.9949874371066271E+00   0.7105427357601002E-14
 FLOPP:  48   0.9949874371066200E+00   0.3534905478043342E-14   0.9949874371066235E+00   0.3552713678800501E-14
 FLOPP:  49   0.9949874371066200E+00   0.1767452739021671E-14   0.9949874371066217E+00   0.1776356839400250E-14
 FLOPP:  50   0.9949874371066200E+00   0.8837263695108355E-15   0.9949874371066209E+00   0.8881784197001252E-15
 FLOPP:  51   0.9949874371066200E+00   0.4418631847554177E-15   0.9949874371066204E+00   0.4440892098500626E-15
 FLOPP:  52   0.9949874371066200E+00   0.2209315923777089E-15   0.9949874371066202E+00   0.2220446049250313E-15
 FLOPP:  53   0.9949874371066200E+00   0.1104657961888544E-15   0.9949874371066201E+00   0.1110223024625157E-15
 FLOPP:  54   0.9949874371066200E+00   0.5523289809442722E-16   0.9949874371066200E+00   0.0000000000000000E+00

                        ************************************************************************************
                        *                       EVALUATE FLOATING POINT ARITHMETIC                         *
                        ************************************************************************************
                        *                                                                                  *
                        * FLOATING POINT PROCESSOR HAS APPROXIMATELY 15 SIGNIFICANT DIGITS                 *
                        *                                                                                  *
                        * DEFAULT VALUE OF INCREMENT FACTOR FOR NUMERICAL DERIVATIVES IS DFAC = 0.1051E-07 *
                        * DEFAULT VALUE FOR DFAC WILL BE USED                                              *
                        *                                                                                  *
                        ************************************************************************************


 ==================================================================================================================================
      ARRAY DIMENSIONS (SEE FILE maxsize.inc)
 ----------------------------------------------------------------------------------------------------------------------------------
      MAXEL     =  100000      Maximum number of elements
      MAXCON    =  200000      Maximum number of connections
      MAXK      =       3      Maximum number of components
      MAXEQ     =       3      Maximum number of equations
      MAXPH     =       3      Maximum number of phases
      MAXB      =       6      Maximum number of phase-dependent secondary variables
      MAXSS     =    1000      Maximum number of sinks/sources
      MAVTAB    =     100      Maximum average number of table entries per sink/source
      MAXROC    =     200      Maximum number of rock types
      MAXTSP    =       5      Maximum number of specified time steps, divided by eight
      MAXLAY    =      10      Maximum number of reservoir layers for wells on deliverability
      MXRPCP    =      14      Maximum number of parameters for relative permeability and capillary pressure functions
      MXPCTB    =       5      Maximum number of points in table for ECM capillary pressure
      MXTBC     =       5      Maximum number of elements with time vs. boundary condition
      MXTBCT    =     100      Maximum number of time vs. pressure data
      MAXTIM    =    1000      Maximum number of calibration times
      MAXN      =      40      Maximum number of parameters to be estimated
      MAXO      =     100      Maximum number of datasets
      MAXM      =    1400      Maximum number of calibration points
      MAXPD     =    1000      Maximum number of paired data
      MAXR      =     100      Maximum number of elements or indices of each parameter or observation
      MAXBRK    =      20      Maximum number of points in time at which SAVE file is written for restart
      MAXEBRK   =      50      Maximum number of elements with new initial conditions after restart
      MAXCOEFF  =       5      Maximum number of coefficients for data modeling functions
      MAXMCS    =    1000      Maximum number of Monte Carlo simulations
      MAXCURVE  =    1000      Maximum number of curves to be plotted
      MAXXGR    =       3      Dimension of third index of array XGUESSR
      MTYPE     =      26      Number of observation types
      MPFMT     =       6      Number of plot file formats 
 ----------------------------------------------------------------------------------------------------------------------------------


 ----------------------------------------------------------------------------------------------------------------------------------
      PROGRAM  VERSION   DATE                  COMMENT
 ----------------------------------------------------------------------------------------------------------------------------------
      iTOUGH2            Current version       iTOUGH2 V6.6 (MARCH, 2011)                                                                                                                                                                                                                                      
 ----------------------------------------------------------------------------------------------------------------------------------
      iTOUGH   1.0       1 AUGUST    1992      ITOUGH User's Guide, Version 1.0, Report NIB 92-99
      iTOUGH2  2.2       1 FEBRUARY  1994      iTOUGH2 User's Guide, Version 2.2, Report LBL-34581
      iTOUGH2  3.0      12 JULY      1996      YMP Software qualification, Report LBNL-39489
      iTOUGH2  3.1       1 APRIL     1997      iTOUGH2 Command Reference, Version 3.1, Report LBNL-40041
      iTOUGH2  3.2      30 JUNE      1998      YMP Software Qualification, Report LBNL-42002
      iTOUGH2  3.3       1 OCTOBER   1998      Parallelization using PVM, Report LBNL-42261
      iTOUGH2  4.0      19 JANUARY   1999      Released by Energy Science and Technology Software Center
      iTOUGH2  5.0      31 JULY      2002      Qualified for use within Yucca Mountain Project
 ----------------------------------------------------------------------------------------------------------------------------------

      WHATCOM  1.0      10 AUGUST    1993      Q: WHAT COMPUTER IS USED? A: LINUX
      CALLSIG  1.0       5 DECEMBER  1995      #112: SIGNAL HANDLER
      CPUSEC   1.0      10 AUGUST    1993      RETURNS CPU-TIME (VERSION LINUX)
      OPENFILE 6.5      15 APRIL     2010      OPENS MOST OF THE FILES
      LENOS    1.0       1 MARCH     1992      RETURNS LENGTH OF LINE
      PREC     1.0       1 AUGUST    1992      CALCULATE MACHINE DEPENDENT CONSTANTS
      ITHEADER 3.2      27 MAY       1998      PRINTS iTOUGH2 HEADER
      DAYTIM   1.0      10 AUGUST    1993      RETURNS DATE AND TIME (VERSION SUN)
      THEADER  6.0      29 JUNE      2007      PRINTS TOUGH2 HEADER
      SOLVTYPE 1.0       1 OCTOBER   1999      INITIALIZE PARAMETERS FOR THE SOLVER PACKAGE
      INPUT    6.4       5 MARCH     2009      READ ALL DATA PROVIDED THROUGH FILE *INPUT*
      CHECKMAX 6.0       4 FEBRUARY  2008      CHECK KEY DIMENSIONS
      FLOPP    6.5      15 APRIL     2010      CALCULATE NUMBER OF SIGNIFICANT DIGITS FOR FLOATING POINT ARITHMETIC
      RFILE    6.5       8 FEBRUARY  2010      INITIALIZE DATA FROM FILES *MESH* OR *MINC*, *GENER*, AND *INCON*
      ITINPUT  1.0       1 AUGUST    1992      READS COMMANDS OF COMMAND LEVEL 1
      READCOMM 6.6      12 APRIL     2011      READS A COMMAND
      FINDKEY  6.5      15 APRIL     2010      READS A KEYWORD
      LTU      1.0       1 AUGUST    1992      CONVERTS LOWER TO UPPER CASE
      GETINDEX 6.6      20 NOVEMBER  2011      GETS INDEX OF ELEMENTS, CONNECTIONS, AND SOURCES
      INIGUESS 6.5      15 APRIL     2010      ASSIGN DEFAULT INITIAL PARAMETER GUESS
      IXLBXUB  2.1      21 SEPTEMBER 1993      INITIALIZES ARRAY XLB AND XUB
      ADDNOISE 6.6      20 NOVEMBER  2011      ADDS NOISE TO SYNTHETIC DATA
      TIMEWIND 6.5      31 MARCH     2010      SETS TIME WINDOW
      SETWSCAL 6.6      17 NOVEMBER  2011      INITIALIZES ARRAY WSCALE
      OBSMEAN  6.6      20 NOVEMBER  2011      CALCULATES MEAN OF OBSERVATIONS
      SETXSCAL 1.0       1 AUGUST    1992      INITIALIZES ARRAY XSCALE
      IN_OUT   6.4      20 JANUARY   2009      PRINTS A SUMMARY OF INPUT DATA
      PRSTATUS 3.1      20 FEBRUARY  1997      PRINTS STATUS MESSAGES
      ERRORMSG 5.1      19 SEPTEMBER 2005      PRINTS ERROR MESSAGES
      FCNLEV   5.0      12 JULY      2002      RETURNS WEIGHTED RESIDUAL VECTOR
      UPDATE   6.5      15 APRIL     2010      UPDATES PARAMETERS
      PRIORINF 2.1      21 SEPTEMBER 1993      PRIOR INFORMATION
      OBSERVAT 6.6     17 NOVEMBER   2011      COMPARES MEASURED AND CALCULATED QUANTITIES
      GETMESH  3.2      20 JUNE      1998      READS FILE MESH, MINC, GENER, AND INCON
      GETINCON 6.5      15 APRIL     2010      READS FILE INCON
      INITTOUG 6.6       3 AUGUST    2011      INITIALIZES TOUGH2 RUN (REPLACES CYCIT)
      EOS      1.0cd    18 DECEMBER  2007      *ECO2* THERMOPHYSICAL PROPERTIES MODULE FOR H2O/NACL/CO2
                                               USING H2O-CO2 PHASE PARTITIONING ACCORDING TO SPYCHER AND PRUESS, LBNL-56334, SEPTEMBER 04
      HALITE   1.0      25 FEBRUARY  1993      EQUILIBRIUM HALITE SOLUBILITY

      PVTCX    1.0      11 MAY       2005      H2O-CO2 PHASE PARTITIONING FOR BRINES (NIC SPYCHER, LBNL)
                                               OUTPUT MASS FRACTIONS (K.P.)

      FUGA     1.0      13 MAY       2005      CALCULATE H2O-CO2 FUGACITY COEFFICIENTS (NIC SPYCHER, LBNL)
      NCG      1.1       8 AUGUST    2005      SPECIFIC ENTHALPY, DENSITY, AND VISCOSITY OF GASEOUS CO2

      YH2O     1.0       8 AUGUST    2005      CALCULATE H2O AND CO2 MOL FRACTIONS (NIC SPYCHER, LBNL)

      CALC_GAM 1.0      16 FEBRUARY  2005      CALCULATE CO2 ACTIVITY COEFFICIENT (NIC SPYCHER, LBNL)
      DHAL     1.0      11 MARCH     1996      HALITE DENSITY AS FUNCTION OF T AND P
      SAT_67   4.2 MOS  16 JULY      1999      STEAM TABLE EQUATION: SATURATION PRESSURE AS FUNCTION OF TEMPERATURE
      SATB     1.0      26 MARCH     1992      VAPOR PRESSURE OF BRINE AS FUNCTION OF T, P AND SALT MASS FRACTION
      COBRI    1.1       2 JUNE      2005      DENSITY AND ENTHALPY OF LIQUID BRINE AS FUNCTION OF T, P AND SALT MASS FRACTION
                                               CHOOSE BRINE ENTHALPY CORRELATION BY IE(15); DEFAULT IS LORENZ ET AL. (2000)
      COWAT_67 4.2 MOS  16 JULY      1999      LIQUID WATER DENSITY AND INT. ENERGY AS FUNCTION OF TEMPERATURE AND PRESSURE
      TCRITIC  1.0       5 NOVEMBER  1996      CRITICAL T OF NACL SOLUTIONS AS A FUNCTION OF SALINITY
      BRINEN   1.0       5 OCTOBER   2000      DEVIATION OF BRINE ENTHALPY VS. T AND SALT MASS FRACTION AFTER LORENZ ET AL. (2000)
      MOVO     1.0      25 March     2005      MOLAR VOLUME OF DISSOLVED CO2 AFTER J. GARCIA, LBNL-49023
      VISB     1.1       2 June      2005      VISCOSITY OF BRINE AS FUNCTION OF T, P AND SALT MASS FRACTION
      VISH2O   1.0 E    22 MARCH     1996      VISCOSITY OF LIQUID WATER OR VAPOR (ASME, 1977)
      SOLUT    1.2       2 JUNE      2005      HEAT OF SOLUTION OF CO2 AS FUNCTION OF T AND SALT MASS FRACTION
      PCAP     5.2cd    18 DECEMBER  2007      CAPILLARY PRESSURE FUNCTIONS
      AKREL    1.0      30 MAY       1993      PERMEABILITY REDUCTION FACTOR AS FUNCTION OF POROSITY REDUCTION
      HHAL     1.0       5 NOVEMBER  1999      HALITE SPECIFIC ENTHALPY AS FUNCTION OF T

      BALLA    1.13     13 MAY       2005      PERFORM SUMMARY BALANCES FOR VOLUME, MASS, AND ENERGY
      CALLTOUG 6.4      15 FEBRUARY  2009      CALLS TOUGH2 FOR ONE TIME STEP
      MULTI    6.4       9 OCTOBER   2009      ASSEMBLE ALL ACCUMULATION AND FLOW TERMS
      QU       6.4      12 NOVEMBER  2009      ASSEMBLE ALL SOURCE AND SINK TERMS
                                               "RIGOROUS" STEP RATE CAPABILITY FOR MOP(12) = 2
      LINEQ    2.1      30 JANUARY   2007      INTERFACE FOR LINEAR EQUATION SOLVERS
      CONVER   6.4      20 FEBRUARY  2009      UPDATE PRIMARY VARIABLES AFTER CONVERGENCE IS ACHIEVED
      RELP     4.5cd    18 DECEMBER  2007      RELATIVE PERMEABILITIES

      OUT      1.1cd    18 DECEMBER  2007      PRINT RESULTS FOR ELEMENTS, CONNECTIONS, AND SINKS/SOURCES
      TERMINAT 6.5      27 JANUARY   2010      PERFORM ERROR ANALYSIS AND TERMINATE iTOUGH2
      PLOTFILE 6.6      15 MARCH     2011      WRITES PLOTFILE IN TECPLOT-FORMAT
      WRIFI    6.5      15 APRIL     2010      AT THE COMPLETION OF A TOUGH2 RUN, WRITE PRIMARY VARIABLES ON FILE *SAVE*

 ==================================================================
      S T A T U S   O F   i T O U G H 2   S I M U L A T I O N
 ==================================================================

 Date                        : 25-Feb-13  17:57
 iTOUGH2 file                : invdir
 TOUGH2 file                 : CO2_fwd
 Working directory           : /home/flo/04_iTOUGH2/CO2_paper/test_mc/mc_lowres
 Temporary directory         : /home/flo/it2_30237
 UNIX command line arguments : -tough2 -no_delete -m MESH CO2_fwd.dat 17
 Comment                     : Input files read.                                                              

 Iterations completed        :              0    Iterations to go      1
 TOUGH2 runs completed       :              0    Unsuccessful steps    0
 TOUGH2 runs to go (approx.) :              1    Log(Levenberg)        0
 CPU time used [sec]         :           0.02    for last step      0.02
                                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
                                        @                                             @
                                        @   @  @@@@@   @@   @  @   @@@  @  @   @@@@   @
                                        @        @    @  @  @  @  @     @  @  @    @  @
                                        @   @    @    @  @  @  @  @ @@  @@@@     @@   @
                                        @   @    @    @  @  @  @  @  @  @  @    @@    @
                                        @   @    @     @@    @@    @@@  @  @  @@@@@@  @
                                        @                                             @
                                        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

                                       iTOUGH2 V6.6 (MARCH, 2011) FOR LINUX, S. FINSTERLE 
                                COPYRIGHT (C) 2007, THE REGENTS OF THE UNIVERSITY OF CALIFORNIA
                                     THROUGH LAWRENCE BERKELEY NATIONAL LABORATORY
                                                  ALL RIGHTS RESERVED

 ==================================================================================================================================
                                          >>>>>>>>>>>>> 25-Feb-13  17:57 <<<<<<<<<<<<<
 ==================================================================================================================================
 iTOUGH2 RUN NO.               :     1
 iTOUGH2 INPUT FILE            :  invdir
 TOUGH2 INPUT FILE             :  CO2_fwd
 WORKING DIRECTORY             :  /home/flo/04_iTOUGH2/CO2_paper/test_mc/mc_lowres
 TEMPORARY DIRECTORY           :  /home/flo/it2_30237
 EQUATION OF STATE MODULE NO.  :    17 --> Two-phase, non-isothermal flow of water, NaCl and CO2
 COMPONENTS                    :  WATER     NaCl      CO2       HEAT                          
 PHASES                        :  GAS       LIQUID    SALT      
 TOUGH2 TITLE                  :  *rcc3* ... CO2 example - leakage over fault in uncertain distance               
 ==================================================================================================================================

 **********************************************************************************************************************************
                                                              INPUT
 **********************************************************************************************************************************


 PARAMETERS
 ==========

 ----------------------------------------------------------------------------------------------------------------------------------
  # ID ANNOTATION       PARAMETER TYPE   V/L/F  ROCKS    PRIOR INFO.     STD. DEV. LOWER BOUND  UPPER BOUND    MAX. STEP  PAR
 ----------------------------------------------------------------------------------------------------------------------------------
 ----------------------------------------------------------------------------------------------------------------------------------


 OBSERVATIONS
 ============

 TIMES [sec]                                         
 -----------


 ----------------------------------------------------------------------------------------------------------------------------------
 SET ANNOTATION      DATATYPE        ELEME/CONNE       STD. DEV. MIN. TIME MAX. TIME LOG(V/M/S)     #DATA #CALI     FACTOR  IOBS
 ----------------------------------------------------------------------------------------------------------------------------------
 ----------------------------------------------------------------------------------------------------------------------------------


 --------------------------------------------------
 Number of datasets                    :    0
 Number of calibration times           :    0                                          
 Number of parameters specified        :    0
 Number of TOUGH-related parameters    :    0
 Number of TOUGH-independent parameters:    0
 Number of inactive parameters         :    0
 Number of tied parameters             :    0
 Number of free parameters         (n) :    0
 Number of superparameters (max.)      :    0
 Number of parameters with prior info. :          0
 Number of regularization terms        :          0
                                              -----
 Total number of observations      (m) :          0                                    
                                              =====
 Degree of freedom               (m-n) :    0
 --------------------------------------------------


 COMPUTATIONAL PARAMETERS
 ========================

 Application                                     :                   Forward Run                                                  
 Maximum number of iTOUGH2 iterations            :                             1
 Maximum number of TOUGH2 calls                  :                             1
 Maximum number of uphill steps                  :                            10
 Maximum size of scaled parameter step           :                     unlimited
 Initial Levenberg parameter                     :                   0.10000E+01
 Marquardt parameter                             :                  -0.10000E+02
 Finite difference quotient for Jacobian         :                       forward
 Diagonal of Tikhonov matrix                     :                         (N/A)
 Automatic FD update of Jacobian                 :                             0
 Skip iterations with FD update of Jacobian      :                             0
 Broyden rank-one update of Jacobian             :                             0
 Increment factor for computing derivatives      :                   0.10000E-01
 Variance for error analysis                     :                  a posteriori
 Format of plotfile                              :                       Tecplot
 Objective Function                              :                 Least-Squares


 COMPUTER SYSTEM
 ===============

 Machine type                                    : Linux               
 UNIX script file name                           : /home/flo/bin/itough2                                                           
 UNIX command line arguments                     : -tough2 -no_delete -m MESH CO2_fwd.dat 17
 Host name                                       : AbaqusARRC
 User name                                       : flo
 Executable                                      : /home/flo/itough2v6.5/Executable/itough2_17


 --- End of iTOUGH2 input job:    1 lines read,    0.02 CPU-seconds used


 **********************************************************************************************************************************
                                                              OUTPUT
 **********************************************************************************************************************************


 SOLVE DIRECT PROBLEM                                        

 I  = NEW ITERATION        J  = JACOBIAN           S  = STEP      U  = UNSUCCESSFUL STEP
 PS = PARAMETER SELECTION  PU = PARAMETER UPDATE   B  = BOUNDS    M  = MESSAGE

 ----------------------------------------------------------------------------------------------------------------------------------
 ITER TOUGH2 OBJ FUNC. MAX. RESID. EQU.

 >>>>>  Forward run terminated at simulation time  0.32000000E+10 [sec] <<<<<


 ---  4897th iTOUGH2 run stopped (forward run) on 25-Feb-13  17:58 ---  CPU time used =      58.88 sec.

 ---     0 error(s) and  0 warning(s) detected
